spring:
  application:
    name:
      comments-service

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    driverClassName:
      org.postgresql.Driver
    url:
      *your url*
    username:
      *your username*
    password:
      *your password*

server:
  port:
    8082
