version: 2.27.0
services:
  blog-post-frontend:
    build:
      context: ../
      dockerfile: Dockerfile
    image: mmaksymko/blog-post-frontend:latest
    environment:
      BLOGPOST_BACKEND_HOST: ${BLOGPOST_BACKEND_HOST:-http://localhost}
      BLOGPOST_BACKEND_PORT: ${BLOGPOST_BACKEND_PORT:-8080}
    ports:
      - "3000:80"
    networks:
      blogpost-network:
        aliases:
          - "blog-post-frontend"
networks:
  blogpost-network:
    external: true