spring:
  application:
    name:
      config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/mmaksymko/blogpost-config
          search-paths: '{application}'
  profiles:
    active: dev

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

encrypt:
  key: ${BLOGPOST_ENCRYPTION_KEY}

server:
  port:
    8071