spring:
  application:
    name:
      config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/mmaksymko/blogpost-config
          search-paths: '{application}'
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

encrypt:
  key: ${BLOGPOST_ENCRYPTION_KEY:encryption-key}

server:
  port:
    8071